/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { OpenAppService } from "../openApp.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OpenAppCreateInput } from "./OpenAppCreateInput";
import { OpenAppWhereInput } from "./OpenAppWhereInput";
import { OpenAppWhereUniqueInput } from "./OpenAppWhereUniqueInput";
import { OpenAppFindManyArgs } from "./OpenAppFindManyArgs";
import { OpenAppUpdateInput } from "./OpenAppUpdateInput";
import { OpenApp } from "./OpenApp";
import { BotAppFindManyArgs } from "../../botApp/base/BotAppFindManyArgs";
import { BotApp } from "../../botApp/base/BotApp";
import { BotAppWhereUniqueInput } from "../../botApp/base/BotAppWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OpenAppControllerBase {
  constructor(
    protected readonly service: OpenAppService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OpenApp })
  @nestAccessControl.UseRoles({
    resource: "OpenApp",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: OpenAppCreateInput,
  })
  async create(@common.Body() data: OpenAppCreateInput): Promise<OpenApp> {
    return await this.service.create({
      data: data,
      select: {
        activate: true,
        appId: true,
        appName: true,
        appSecret: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [OpenApp] })
  @ApiNestedQuery(OpenAppFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "OpenApp",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<OpenApp[]> {
    const args = plainToClass(OpenAppFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        activate: true,
        appId: true,
        appName: true,
        appSecret: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OpenApp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OpenApp",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: OpenAppWhereUniqueInput
  ): Promise<OpenApp | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        activate: true,
        appId: true,
        appName: true,
        appSecret: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OpenApp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OpenApp",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: OpenAppUpdateInput,
  })
  async update(
    @common.Param() params: OpenAppWhereUniqueInput,
    @common.Body() data: OpenAppUpdateInput
  ): Promise<OpenApp | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          activate: true,
          appId: true,
          appName: true,
          appSecret: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OpenApp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "OpenApp",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: OpenAppWhereUniqueInput
  ): Promise<OpenApp | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          activate: true,
          appId: true,
          appName: true,
          appSecret: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/botApp")
  @ApiNestedQuery(BotAppFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BotApp",
    action: "read",
    possession: "any",
  })
  async findManyBotApp(
    @common.Req() request: Request,
    @common.Param() params: OpenAppWhereUniqueInput
  ): Promise<BotApp[]> {
    const query = plainToClass(BotAppFindManyArgs, request.query);
    const results = await this.service.findBotApp(params.id, {
      ...query,
      select: {
        apiEndPoint: true,
        apiSecret: true,
        appDesc: true,
        appName: true,
        createdAt: true,
        id: true,
        inputs: true,

        openApps: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        welcome: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/botApp")
  @nestAccessControl.UseRoles({
    resource: "OpenApp",
    action: "update",
    possession: "any",
  })
  async connectBotApp(
    @common.Param() params: OpenAppWhereUniqueInput,
    @common.Body() body: BotAppWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      botApp: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/botApp")
  @nestAccessControl.UseRoles({
    resource: "OpenApp",
    action: "update",
    possession: "any",
  })
  async updateBotApp(
    @common.Param() params: OpenAppWhereUniqueInput,
    @common.Body() body: BotAppWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      botApp: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/botApp")
  @nestAccessControl.UseRoles({
    resource: "OpenApp",
    action: "update",
    possession: "any",
  })
  async disconnectBotApp(
    @common.Param() params: OpenAppWhereUniqueInput,
    @common.Body() body: BotAppWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      botApp: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
