/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BotAppService } from "../botApp.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BotAppCreateInput } from "./BotAppCreateInput";
import { BotAppWhereInput } from "./BotAppWhereInput";
import { BotAppWhereUniqueInput } from "./BotAppWhereUniqueInput";
import { BotAppFindManyArgs } from "./BotAppFindManyArgs";
import { BotAppUpdateInput } from "./BotAppUpdateInput";
import { BotApp } from "./BotApp";
import { OpenAppFindManyArgs } from "../../openApp/base/OpenAppFindManyArgs";
import { OpenApp } from "../../openApp/base/OpenApp";
import { OpenAppWhereUniqueInput } from "../../openApp/base/OpenAppWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BotAppControllerBase {
  constructor(
    protected readonly service: BotAppService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BotApp })
  @nestAccessControl.UseRoles({
    resource: "BotApp",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: BotAppCreateInput,
  })
  async create(@common.Body() data: BotAppCreateInput): Promise<BotApp> {
    return await this.service.create({
      data: data,
      select: {
        apiEndPoint: true,
        apiSecret: true,
        appDesc: true,
        appName: true,
        createdAt: true,
        id: true,
        inputs: true,
        updatedAt: true,
        welcome: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BotApp] })
  @ApiNestedQuery(BotAppFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BotApp",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<BotApp[]> {
    const args = plainToClass(BotAppFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        apiEndPoint: true,
        apiSecret: true,
        appDesc: true,
        appName: true,
        createdAt: true,
        id: true,
        inputs: true,
        updatedAt: true,
        welcome: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BotApp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BotApp",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: BotAppWhereUniqueInput
  ): Promise<BotApp | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        apiEndPoint: true,
        apiSecret: true,
        appDesc: true,
        appName: true,
        createdAt: true,
        id: true,
        inputs: true,
        updatedAt: true,
        welcome: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BotApp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BotApp",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: BotAppUpdateInput,
  })
  async update(
    @common.Param() params: BotAppWhereUniqueInput,
    @common.Body() data: BotAppUpdateInput
  ): Promise<BotApp | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          apiEndPoint: true,
          apiSecret: true,
          appDesc: true,
          appName: true,
          createdAt: true,
          id: true,
          inputs: true,
          updatedAt: true,
          welcome: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BotApp })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BotApp",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: BotAppWhereUniqueInput
  ): Promise<BotApp | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          apiEndPoint: true,
          apiSecret: true,
          appDesc: true,
          appName: true,
          createdAt: true,
          id: true,
          inputs: true,
          updatedAt: true,
          welcome: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/openApps")
  @ApiNestedQuery(OpenAppFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "OpenApp",
    action: "read",
    possession: "any",
  })
  async findManyOpenApps(
    @common.Req() request: Request,
    @common.Param() params: BotAppWhereUniqueInput
  ): Promise<OpenApp[]> {
    const query = plainToClass(OpenAppFindManyArgs, request.query);
    const results = await this.service.findOpenApps(params.id, {
      ...query,
      select: {
        activate: true,
        appId: true,
        appName: true,
        appSecret: true,

        botApp: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/openApps")
  @nestAccessControl.UseRoles({
    resource: "BotApp",
    action: "update",
    possession: "any",
  })
  async connectOpenApps(
    @common.Param() params: BotAppWhereUniqueInput,
    @common.Body() body: OpenAppWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      openApps: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/openApps")
  @nestAccessControl.UseRoles({
    resource: "BotApp",
    action: "update",
    possession: "any",
  })
  async updateOpenApps(
    @common.Param() params: BotAppWhereUniqueInput,
    @common.Body() body: OpenAppWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      openApps: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/openApps")
  @nestAccessControl.UseRoles({
    resource: "BotApp",
    action: "update",
    possession: "any",
  })
  async disconnectOpenApps(
    @common.Param() params: BotAppWhereUniqueInput,
    @common.Body() body: OpenAppWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      openApps: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
